codecov:
  branch: master

coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project:
      default:
        enabled: yes
        target: auto

comment:
  layout: "header, diff, tree"
  behavior: default
